server:
  port: 8080
hds:
  gfx:
    controller:
      thumbnail:
        permits: 1
      hvif2png:
        permits: 16
# Quantize the image; false by default
#    quantize: false
  tool:
    convert:
      limit-memory: 60MB
      limit-disk: 0MB
    oxipng:
# TODO; remove this placeholder once the config systems supports this.
      path: /x/y/z/oxipng
    hvif2png:
# TODO; remove this placeholder once the config systems supports this.
      path: /w/u/v/hvifpng